/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regla_falsa_trigonometrica;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author MAYRA
 */
public class grados_radianes extends javax.swing.JFrame {

    /**
     * Creates new form grados_radianes
     */
    public grados_radianes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        rbtngrados = new javax.swing.JRadioButton();
        rbtnradianes = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnGrados = new javax.swing.JMenuItem();
        btnRadianes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));

        jpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbtngrados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtngrados.setText("Grados");
        rbtngrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtngradosActionPerformed(evt);
            }
        });

        rbtnradianes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtnradianes.setText("Radianes");
        rbtnradianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnradianesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Escoge tu manejo de intervalos");

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(rbtngrados)
                        .addGap(139, 139, 139)
                        .addComponent(rbtnradianes))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtngrados)
                    .addComponent(rbtnradianes))
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        btnGrados.setText("Grados");
        btnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradosActionPerformed(evt);
            }
        });
        jMenu1.add(btnGrados);

        btnRadianes.setText("Radianes");
        btnRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadianesActionPerformed(evt);
            }
        });
        jMenu1.add(btnRadianes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("info");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnradianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnradianesActionPerformed
        // TODO add your handling code here:
        
        Radianes r=new Radianes();
        panel(r);
        
    }//GEN-LAST:event_rbtnradianesActionPerformed

    private void rbtngradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtngradosActionPerformed
        // TODO add your handling code here:
        Grados g=new Grados();
        panel(g);
    }//GEN-LAST:event_rbtngradosActionPerformed

    private void btnGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradosActionPerformed
        // TODO add your handling code here:
        
         Grados g=new Grados();
        panel(g);
        
    }//GEN-LAST:event_btnGradosActionPerformed

    private void btnRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadianesActionPerformed
        // TODO add your handling code here:
        
        Radianes r=new Radianes();
        panel(r);
        
    }//GEN-LAST:event_btnRadianesActionPerformed
public void panel(JPanel p){
        p.setSize(700, 700);
        p.setLocation(0, 0);
       jpanel.removeAll();
       jpanel.add(p, BorderLayout.CENTER);
       jpanel.revalidate();
       jpanel.repaint();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grados_radianes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grados_radianes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grados_radianes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grados_radianes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grados_radianes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnGrados;
    private javax.swing.JMenuItem btnRadianes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JRadioButton rbtngrados;
    private javax.swing.JRadioButton rbtnradianes;
    // End of variables declaration//GEN-END:variables
}
