/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regla_falsa_trigonometrica;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author MAYRA
 */
public class Metodo_Secantes extends javax.swing.JFrame {

    static double xa = 0, xb = 0, xrm = 0, xr, fxa = 0, fxr = 0, count, xrn = 0, fxav, fxb, xrw, XRN = 0, XRNV = 0, ERROR = 0, comp = 0;
    static double valor = 0, valor1 = 0, valor2 = 0, valor3 = 0, valor4 = 0, valor5 = 0, valor6 = 0, intervalo1 = 0, intervalo2 = 0, err = 0;
    static int redondeo = 0;

    /**
     * Creates new form Metodo_Secantes
     */
    public Metodo_Secantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtconstante = new javax.swing.JTextField();
        lblConstante = new javax.swing.JLabel();
        txtgrado1 = new javax.swing.JTextField();
        lblGrado1 = new javax.swing.JLabel();
        lblGrado2 = new javax.swing.JLabel();
        txtgrado2 = new javax.swing.JTextField();
        lblGrado3 = new javax.swing.JLabel();
        txtgrado3 = new javax.swing.JTextField();
        lblGrado4 = new javax.swing.JLabel();
        txtgrado4 = new javax.swing.JTextField();
        lblGrado5 = new javax.swing.JLabel();
        txtgrado5 = new javax.swing.JTextField();
        lblGrado6 = new javax.swing.JLabel();
        txtgrado6 = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        txterror = new javax.swing.JTextField();
        lblDecimales = new javax.swing.JLabel();
        txtredondeo = new javax.swing.JTextField();
        lblIntervalo1 = new javax.swing.JLabel();
        lblIntervalo2 = new javax.swing.JLabel();
        txtintervalo1 = new javax.swing.JTextField();
        txtintervalo2 = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        txtconstante.setMaximumSize(new java.awt.Dimension(55, 22));
        txtconstante.setMinimumSize(new java.awt.Dimension(55, 22));
        txtconstante.setPreferredSize(new java.awt.Dimension(55, 22));
        txtconstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconstanteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconstanteKeyTyped(evt);
            }
        });

        lblConstante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConstante.setText("Constante");
        lblConstante.setMinimumSize(new java.awt.Dimension(63, 16));
        lblConstante.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado1.setMaximumSize(null);
        txtgrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado1KeyTyped(evt);
            }
        });

        lblGrado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado1.setText("1°Grado");
        lblGrado1.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado1.setPreferredSize(new java.awt.Dimension(63, 16));

        lblGrado2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado2.setText("2°Grado");
        lblGrado2.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado2.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado2.setMaximumSize(null);
        txtgrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado2KeyTyped(evt);
            }
        });

        lblGrado3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado3.setText("3°Grado");
        lblGrado3.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado3.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado3.setMaximumSize(null);
        txtgrado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrado3ActionPerformed(evt);
            }
        });
        txtgrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado3KeyTyped(evt);
            }
        });

        lblGrado4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado4.setText("4°Grado");
        lblGrado4.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado4.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado4.setMaximumSize(null);
        txtgrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado4KeyTyped(evt);
            }
        });

        lblGrado5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado5.setText("5°Grado");
        lblGrado5.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado5.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado5.setMaximumSize(null);
        txtgrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado5KeyTyped(evt);
            }
        });

        lblGrado6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado6.setText("6°Grado");
        lblGrado6.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado6.setPreferredSize(new java.awt.Dimension(63, 16));

        txtgrado6.setMaximumSize(null);
        txtgrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgrado6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrado6KeyTyped(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblError.setText("Error deseado");
        lblError.setMaximumSize(new java.awt.Dimension(55, 22));
        lblError.setMinimumSize(new java.awt.Dimension(55, 22));
        lblError.setName(""); // NOI18N

        txterror.setMaximumSize(new java.awt.Dimension(55, 22));
        txterror.setMinimumSize(new java.awt.Dimension(55, 22));
        txterror.setName(""); // NOI18N
        txterror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txterrorActionPerformed(evt);
            }
        });
        txterror.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txterrorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txterrorKeyTyped(evt);
            }
        });

        lblDecimales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDecimales.setText("N° Redondeo");
        lblDecimales.setMaximumSize(new java.awt.Dimension(55, 22));
        lblDecimales.setMinimumSize(new java.awt.Dimension(55, 22));
        lblDecimales.setName(""); // NOI18N

        txtredondeo.setMaximumSize(new java.awt.Dimension(55, 22));
        txtredondeo.setMinimumSize(new java.awt.Dimension(55, 22));
        txtredondeo.setName(""); // NOI18N
        txtredondeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtredondeoActionPerformed(evt);
            }
        });
        txtredondeo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtredondeoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtredondeoKeyTyped(evt);
            }
        });

        lblIntervalo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIntervalo1.setText("Intervalo 1");
        lblIntervalo1.setToolTipText("");

        lblIntervalo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIntervalo2.setText("Intervalo 2");
        lblIntervalo2.setToolTipText("");

        txtintervalo1.setPreferredSize(new java.awt.Dimension(55, 22));
        txtintervalo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtintervalo1ActionPerformed(evt);
            }
        });
        txtintervalo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtintervalo1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtintervalo1KeyTyped(evt);
            }
        });

        txtintervalo2.setPreferredSize(new java.awt.Dimension(55, 22));
        txtintervalo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtintervalo2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtintervalo2KeyTyped(evt);
            }
        });

        btncalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Metodo secante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConstante, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblGrado3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblGrado4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblGrado5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblGrado6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtconstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtgrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtgrado2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtgrado3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtgrado4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtgrado5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(txtgrado6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txterror, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtredondeo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblIntervalo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblIntervalo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtintervalo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtintervalo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btncalcular)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtconstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgrado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txterror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtredondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntervalo1)
                    .addComponent(lblIntervalo2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtintervalo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtintervalo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btncalcular)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtconstanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconstanteKeyReleased
        // TODO add your handling code here:
        //txtConstanteKeyReleased(evt);
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtconstante.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtconstanteKeyReleased

    private void txtconstanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconstanteKeyTyped

    }//GEN-LAST:event_txtconstanteKeyTyped

    private void txtgrado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado1.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado1KeyReleased

    private void txtgrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado1KeyTyped

    }//GEN-LAST:event_txtgrado1KeyTyped

    private void txtgrado2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado2.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado2KeyReleased

    private void txtgrado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado2KeyTyped

    }//GEN-LAST:event_txtgrado2KeyTyped

    private void txtgrado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrado3ActionPerformed

    private void txtgrado3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado3KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado3.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado3KeyReleased

    private void txtgrado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado3KeyTyped

    }//GEN-LAST:event_txtgrado3KeyTyped

    private void txtgrado4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado4KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado4.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado4KeyReleased

    private void txtgrado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado4KeyTyped

    }//GEN-LAST:event_txtgrado4KeyTyped

    private void txtgrado5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado5KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado5.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado5KeyReleased

    private void txtgrado5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado5KeyTyped

    }//GEN-LAST:event_txtgrado5KeyTyped

    private void txtgrado6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado6KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtgrado6.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);
            txtintervalo1.setEnabled(true);
            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);
            txtintervalo1.setEnabled(false);
            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtgrado6KeyReleased

    private void txtgrado6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrado6KeyTyped

    }//GEN-LAST:event_txtgrado6KeyTyped

    private void txterrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txterrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txterrorActionPerformed

    private void txterrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txterrorKeyReleased
        // TODO add your handling code here:

        String nombre = "^[+-]?(\\d*\\.)?\\d+$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txterror.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);

            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);

            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txterrorKeyReleased

    private void txterrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txterrorKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txterrorKeyTyped

    private void txtredondeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtredondeoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtredondeoActionPerformed

    private void txtredondeoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtredondeoKeyReleased
        // TODO add your handling code here:

        String nombre = "^[+-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtredondeo.getText());
        if (match.find()) {

            btncalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);

            return;
        }
    }//GEN-LAST:event_txtredondeoKeyReleased

    private void txtredondeoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtredondeoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtredondeoKeyTyped

    private void txtintervalo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtintervalo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtintervalo1ActionPerformed

    private void txtintervalo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervalo1KeyReleased
        // TODO add your handling code here:

        String nombre = "^[+-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtintervalo1.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);

            txtintervalo2.setEnabled(true);
            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);

        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);

            txtintervalo2.setEnabled(false);
            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);

            return;
        }
    }//GEN-LAST:event_txtintervalo1KeyReleased

    private void txtintervalo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervalo1KeyTyped

    }//GEN-LAST:event_txtintervalo1KeyTyped

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        count = 1;
        intervalo1 = 0;
        intervalo2 = 0;
        err = 0;
        XRN = 0;
        xr = 0;
        String Valor = txtconstante.getText();//constate
        String Valor1 = txtgrado1.getText();//grado 1
        String Valor2 = txtgrado2.getText();//grado 2
        String Valor3 = txtgrado3.getText();//grado 3
        String Valor4 = txtgrado4.getText();//grado 4
        String Valor5 = txtgrado5.getText();//grado 5
        String Valor6 = txtgrado6.getText();//grado 6
        String error = txterror.getText();

        valor = Double.parseDouble(Valor);//conversion
        //System.out.println("VALORD: "+valor);
        valor1 = Double.parseDouble(Valor1);
        //System.out.println("Valor 1d: "+valor1);
        valor2 = Double.parseDouble(Valor2);
        //System.out.println("Valor 2d: "+valor2);
        valor3 = Double.parseDouble(Valor3);
        //System.out.println("ValorD3333333333333333: "+valor3);
        valor4 = Double.parseDouble(Valor4);
        valor5 = Double.parseDouble(Valor5);
        valor6 = Double.parseDouble(Valor6);

        String Xa = txtintervalo1.getText(); //xa=x0//llamamos el dato txtintervalo y lo metemos en una variable string
        xa = Double.parseDouble(Xa);//convertimos de string a double

        String Xb = txtintervalo2.getText(); //xb= x1
        xb = Double.parseDouble(Xb);

        intervalo1 = xa;//grado a radian
        intervalo2 = xb;

        // System.out.println("Digita valorr de b: ");
        // REDONDEO
        String REDO = txtredondeo.getText();
        redondeo = Integer.parseInt(REDO);

        ERROR = Double.parseDouble(error);
        System.out.println("ERRR: " + ERROR);
        normal();
    }//GEN-LAST:event_btncalcularActionPerformed

    private void txtintervalo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervalo2KeyTyped

    }//GEN-LAST:event_txtintervalo2KeyTyped

    private void txtintervalo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintervalo2KeyReleased
        // TODO add your handling code here:

        String nombre = "^[+-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtintervalo2.getText());
        if (match.find()) {
            btncalcular.setEnabled(true);

            txterror.setEnabled(true);
            btncalcular.setEnabled(true);
            txtredondeo.setEnabled(true);
            btncalcular.setEnabled(true);

        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            btncalcular.setEnabled(false);

            txterror.setEnabled(false);
            btncalcular.setEnabled(false);
            txtredondeo.setEnabled(false);

            return;
        }
    }//GEN-LAST:event_txtintervalo2KeyReleased

    public void normal() {

        System.out.println("------CONTADOR-----: " + count);
        System.out.println("tu intervalo 1: " + intervalo1);
        System.out.println("tu intervalo 2: " + intervalo2);

        fxa = ((valor6 * (Math.pow(intervalo1, 6)) + valor5 * (Math.pow(intervalo1, 5)) + valor4 * (Math.pow(intervalo1, 4)) + valor3 * (Math.pow(intervalo1, 3)) + valor2 * (Math.pow(intervalo1, 2)) + valor1 * (Math.pow(intervalo1, 1)) + valor));
        //fxa = ((valor6* (Math.pow(xa, 6))) +(valor5* (Math.pow(xa, 5))) +(valor4* (Math.pow(xa, 4))) +(valor3* (Math.pow(xa, 3))) + (valor2 * (Math.pow(xa, 2))) + ((valor1 * (Math.pow(xa, 1)))) + valor);
        System.out.println("fxa 2: " + String.format("%." + redondeo + "f", fxa));

        fxb = (((valor6 * (Math.pow(intervalo2, 6))) + (valor5 * (Math.pow(intervalo2, 5))) + (valor4 * (Math.pow(intervalo2, 4))) + (valor3 * (Math.pow(intervalo2, 3))) + (valor2 * (Math.pow(intervalo2, 2))) + ((valor1 * (Math.pow(intervalo2, 1)))) + valor));
        System.out.println("fxb: " + String.format("%." + redondeo + "f", fxb));//0

        XRN = intervalo2 - ((fxb * (intervalo1 - intervalo2)) / (fxa - fxb));
        System.out.println("XRN: " + XRN);
        XRNV = XRN;
        Secante();
    }

    public void Secante() {//ya quedo

        // xr = (((fxa * intervalo2) - (fxb * intervalo1)) / (fxa - fxb));//aproximacion -0.083
        //System.out.println("xr: " + xr);
        intervalo1 = xb;
        intervalo2 = XRNV;
        //System.out.println("tu intervalo 1: " + intervalo1);
        //System.out.println("tu intervalo 2: " + intervalo2);

        do {
            count++;
            System.out.println("------CONTADOR-----: " + count);
            System.out.println("tu intervalo 1xb: " + intervalo1);
            System.out.println("tu intervalo 2XRNV: " + intervalo2);
            //xa se calcula para sacar el valor de fxa en su ecuacion
            //fxa = ((valor6* (Math.pow(xa, 6))) +(valor5* (Math.pow(xa, 5))) +(valor4* (Math.pow(xa, 4))) +(valor3* (Math.pow(xa, 3))) + (valor2 * (Math.pow(xa, 2))) + ((valor1 * (Math.pow(xa, 1)))) + valor); //2.0827
            fxa = (valor6 * (Math.pow(intervalo1, 6)) + valor5 * (Math.pow(intervalo1, 5)) + valor4 * (Math.pow(intervalo1, 4)) + valor3 * (Math.pow(intervalo1, 3)) + valor2 * (Math.pow(intervalo1, 2)) + valor1 * (Math.pow(intervalo1, 1)) + valor);
            System.out.println("fxa: " + String.format("%." + redondeo + "f", fxa));//0

            fxb = (((valor6 * (Math.pow(intervalo2, 6))) + (valor5 * (Math.pow(intervalo2, 5))) + (valor4 * (Math.pow(intervalo2, 4))) + (valor3 * (Math.pow(intervalo2, 3))) + (valor2 * (Math.pow(intervalo2, 2))) + ((valor1 * (Math.pow(intervalo2, 1)))) + valor));
            System.out.println("fxb: " + String.format("%." + redondeo + "f", fxb));//0
            XRNV = XRN;
            XRN = intervalo2 - ((fxb * (intervalo1 - intervalo2)) / (fxa - fxb));
            System.out.println("tu raiz es : " + XRN);

            //se hace la formula iterativva XRN
            //xrn
            // XRN = intervalo2 - (((fxb * intervalo1) - (fxb * intervalo2)) / (fxa - fxb));
            //System.out.println("XRN:Raiz: " + String.format("%." + redondeo + "f", XRN));//0
            //System.out.println("fxa: " + fxa);
            err = (Math.abs((XRN - XRNV) / XRN) * 100);
            System.out.println("Error: " + err);
            if (err <= ERROR) {
                count++;
                System.out.println("------CONTADOR------: " + count);
                System.out.println("Raiz final: " + XRN);
                System.out.println("tu error final " + err);
                //System.out.println("tu error es " + err);
                return;
            } else {
                intervalo1 = XRNV;
                intervalo2 = XRN;
                System.out.println("tu intervalo 1 en else: " + intervalo1);
                System.out.println("tu intervalo 2 en else: " + intervalo2);

            }

        } while (count <= 100);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodo_Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodo_Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodo_Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodo_Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodo_Secantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConstante;
    private javax.swing.JLabel lblDecimales;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblGrado2;
    private javax.swing.JLabel lblGrado3;
    private javax.swing.JLabel lblGrado4;
    private javax.swing.JLabel lblGrado5;
    private javax.swing.JLabel lblGrado6;
    private javax.swing.JLabel lblIntervalo1;
    private javax.swing.JLabel lblIntervalo2;
    private javax.swing.JTextField txtconstante;
    private javax.swing.JTextField txterror;
    private javax.swing.JTextField txtgrado1;
    private javax.swing.JTextField txtgrado2;
    private javax.swing.JTextField txtgrado3;
    private javax.swing.JTextField txtgrado4;
    private javax.swing.JTextField txtgrado5;
    private javax.swing.JTextField txtgrado6;
    private javax.swing.JTextField txtintervalo1;
    private javax.swing.JTextField txtintervalo2;
    private javax.swing.JTextField txtredondeo;
    // End of variables declaration//GEN-END:variables
}
